/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BCol: typeof import('bootstrap-vue-next')['BCol']
    BContainer: typeof import('bootstrap-vue-next')['BContainer']
    BRow: typeof import('bootstrap-vue-next')['BRow']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
